### PR TITLE
fix(ci): restore baseline CI to green (unblocks Dependabot sweep)

### PR DESCRIPTION
**Pull request by prince30121**
## Summary

Three latent failures on \`main\` were blocking every open Dependabot PR (#167–#189). None were caused by the dependency bumps themselves — they only surfaced once unpinned tooling drifted forward.

- **\`services/ingest/main.go\`**: \`go build ./...\` fails with \`./main.go:38:5: undefined: envmode\`. The \`envmode.IsDevRuntime\` call introduced in #127 forgot its import line. Added it.
- **\`scripts/run_evals.py\`**: P1 Eval gate raises \`NameError: name '_SUITE_NAMES' is not defined\` because the \`--suite\` argparse \`choices\` tuple referenced a constant that was never authored. Reconstructed the canonical 11-suite tuple from the \`summary["suites"]\` key order in \`main()\`.
- **\`.github/workflows/ci.yml\`**: pinned ruff and mypy to the version ranges declared in each service's \`pyproject.toml\` (\`ruff = "^0.4.4"\`, \`mypy = "^1.10.0"\`). \`pip install ruff mypy\` was unpinned, so ruff 0.15.x adding \`UP037\` enforcement silently broke main. Dependabot bumps to those constraints (#186 mypy, #187 ruff) will need to widen this pin in the same diff.

## Why this is the unblocker for the Dependabot sweep

All 23 open Dependabot PRs (#167–#189) show the same 4-failure pattern as \`main\` itself. Once this lands and the bot PRs rebase, the bumps' own CI signal becomes visible.

## Not in this PR

The remaining \`Web — Vitest smoke tests\` failure (\`SOCInsightsView\` SWR cache leakage between test cases) pre-dates this PR and affects every Dependabot PR equally — it does not block the dependency sweep. Filing as a follow-up so this PR stays focused.

## Test plan

- [x] \`python3 scripts/run_evals.py --help\` enumerates all 11 suite names without raising
- [x] \`go build ./...\` no longer reports the \`envmode\` undefined error (locally + CI run on this branch will confirm)
- [x] \`ruff>=0.4.4,<0.5\` is the same range each service's \`pyproject.toml\` already declares
- [ ] CI on this PR turns green for Python Lint, Go ingest, and P1 Eval gates

### CODE REVIEW

**Comment by prince30121** [comment]
Note: this PR was already merged into main as squash commit `6607e216`. Per a follow-up to the original "umbrella PR" approach, the four root-cause baseline fixes (Go envmode import, eval _SUITE_NAMES, ruff/mypy CI pin, SWR cache leak) are now being cherry-picked directly onto every affected open PR branch (28 in total — 20 Dependabot bumps + 8 human-authored stacks) so each one stands on its own without depending on the merge order of this commit. The original commits `8766519b` and `82d41df3` are still resolvable from `origin/fix/main-ci-baseline` for that purpose.
